name: publish

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Getting all of the md file contents for Ignite 2020
      id: collect
      uses: drguthals/talkswithdrg/2020/ignite/intro-to-github@main
      with:
        file: 2020/ignite/intro-to-github/ignite-shareboard.md
        tracking: 2020/ignite/intro-to-github/tracking.md
    - name: Getting all of the md file contents for Start Dev Change 2020
      id: collect2
      uses: drguthals/talkswithdrg/2020/start-dev-change/intro-to-github@main
      with:
        file: 2020/start-dev-change/intro-to-github/start-dev-change-shareboard.md
    - name: Getting all of the md file contents for MSA Events
      id: collect3
      uses: drguthals/talkswithdrg/2020/msa/intro-to-github@main
      with:
        file: 2020/msa/intro-to-github/msa-shareboard.md
    - name: Getting all of the md file contents for Spring Ignite 2021
      id: collect4
      uses: drguthals/talkswithdrg/2021/spring-ignite/intro-to-github@main
      with:
        file: 2021/spring-ignite/intro-to-github/ignite-shareboard.md
    - name: Copy contents and push
      run: |
          git config user.name Sarah Guthals
          git config user.email sarah@guthals.com
          git add .
          git commit -m "pushing"
          git push

